blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/metrovoc/immersive-memorize/blob/main/README.md
    about: Please check our documentation for answers.
  - name: â“ Ask a Question
    url: https://github.com/metrovoc/immersive-memorize/discussions/new?category=q-a
    about: Please ask and answer questions here.
